import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

/**
 * Cross-Origin Isolation middleware — enables SharedArrayBuffer
 *
 * Two headers are required for `self.crossOriginIsolated === true`:
 *
 *   COOP: same-origin
 *     Isolates the browsing context group to same-origin documents.
 *
 *   COEP: require-corp
 *     Every subresource must be same-origin, or served with CORS, or
 *     carry a Cross-Origin-Resource-Policy header.
 *
 * Why require-corp (not credentialless)?
 *   `credentialless` is the newer, more permissive option (Chrome 96+),
 *   but some browser builds / flag configurations don't fully honour it
 *   for the `crossOriginIsolated` gate. `require-corp` is the original
 *   spec value, supported since Chrome 91, and is universally reliable.
 *
 * Subresource compatibility:
 *   - Next.js _next/static/* → same-origin → always allowed
 *   - HuggingFace model files → loaded via fetch() with CORS mode,
 *     CDN responds with Access-Control-Allow-Origin: * → allowed
 *   - ONNX Runtime WASM files → loaded via fetch() with CORS mode,
 *     cdn.jsdelivr.net responds with Access-Control-Allow-Origin: * → allowed
 *   - /api/video/* → same-origin → always allowed
 *
 * crossOrigin: "anonymous" is set in next.config.mjs so all <script>
 * tags generated by Next.js use CORS mode, which satisfies require-corp.
 */
export function middleware(_request: NextRequest) {
  const response = NextResponse.next();

  response.headers.set("Cross-Origin-Opener-Policy", "same-origin");
  response.headers.set("Cross-Origin-Embedder-Policy", "require-corp");

  return response;
}

// Match ALL routes including _next/static, API routes, etc.
// The document response is what matters for crossOriginIsolated,
// but setting these on subresources is harmless and ensures consistency.
export const config = {
  matcher: ["/(.*)", "/"],
};
